@startuml use-cases-context
!include ../../../utils/settings.puml
skinparam linetype polyline

[*] --> OPENED_FORM_BUILDER

OPENED_FORM_BUILDER --> OPENED_FORM_STRUCTURE_MANAGEMENT
OPENED_FORM_BUILDER --> OPENED_FORM_DATA_MANAGEMENT

OPENED_INPUT_MANAGEMENT --> OPENED_INPUT_MANAGEMENT
note on link
  * Save
  * Update
  * Delete
  * Show
end note

OPENED_FORM_STRUCTURE_MANAGEMENT --> OPENED_FORM_STRUCTURE_MANAGEMENT
note on link
  * Save
  * Update
  * Delete
  * Show
end note
OPENED_FORM_STRUCTURE_MANAGEMENT --> OPENED_INPUT_MANAGEMENT

OPENED_FORM_DATA_MANAGEMENT --> OPENED_FORM_DATA_MANAGEMENT
note on link
  * Save
  * Update
  * Delete
  * Show
end note

OPENED_INPUT_MANAGEMENT --> [*]
OPENED_FORM_STRUCTURE_MANAGEMENT --> [*]
OPENED_FORM_DATA_MANAGEMENT --> [*]
OPENED_FORM_BUILDER --> [*]

@enduml