@startuml deployment

Actor User
node "Client" {
    component Angular <<Frontend>>
}
node "Server" {
    node WebServer
    component FormBuilder <<API REST>>
    component "ASP.NET Core" <<Framework>>
    component "PostgreSQL" <<Database>>
}

User -> Angular
Angular -> WebServer : http
WebServer -right-> FormBuilder 
FormBuilder .down.> "ASP.NET Core" 
FormBuilder ..> "PostgreSQL"
WebServer -down-> "PostgreSQL" 
WebServer -down-> "ASP.NET Core"
@enduml